/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Album;
import model.Faixa;
import model.Playlist;

/**
 *
 * @author anderson
 */
public class CriacaoPlaylist extends javax.swing.JFrame {

    /**
     * Creates new form CriacaoPlaylist
     */
    ArrayList<Faixa> faixas = new ArrayList<Faixa>();
    
    public CriacaoPlaylist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BSelecionarAlbum = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CriarPlaylist = new javax.swing.JButton();
        bSelecionarFaixa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        nomePlaylist = new javax.swing.JTextField();
        listaFaixas = new java.awt.List();
        listaAlbuns = new java.awt.List();
        label1 = new java.awt.Label();
        jIniciar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        listaFaixasSelecionadas = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BSelecionarAlbum.setText("SELECIONAR ALBUNS");
        BSelecionarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSelecionarAlbumActionPerformed(evt);
            }
        });

        jLabel2.setText("FAIXAS");

        CriarPlaylist.setText("CRIAR PLAYLIST");
        CriarPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarPlaylistActionPerformed(evt);
            }
        });

        bSelecionarFaixa.setText("SELECIONAR FAIXAS");
        bSelecionarFaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSelecionarFaixaActionPerformed(evt);
            }
        });

        jLabel3.setText("ALBUNS");

        label1.setText("Nome da nova playlist");

        jIniciar.setText("INICIAR");
        jIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIniciarActionPerformed(evt);
            }
        });

        jLabel4.setText("FAIXAS SELECIONADAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(156, 156, 156))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(CriarPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BSelecionarAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nomePlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bSelecionarFaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(48, 48, 48))
                            .addComponent(listaFaixasSelecionadas, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(listaFaixas, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGap(32, 32, 32))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(listaAlbuns, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(353, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(listaFaixas, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSelecionarFaixa)
                    .addComponent(BSelecionarAlbum))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listaFaixasSelecionadas, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jIniciar)
                        .addGap(25, 25, 25)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomePlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CriarPlaylist)))
                .addGap(20, 20, 20))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(listaAlbuns, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(290, Short.MAX_VALUE)))
        );

        label1.getAccessibleContext().setAccessibleName("sca");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BSelecionarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSelecionarAlbumActionPerformed
        listaFaixas.removeAll();
        Controller controle = new Controller();
        if(listaAlbuns.getSelectedItem() != null){
            String cod_album = listaAlbuns.getSelectedItem().split(" ")[1];
            System.out.println(cod_album);
            ArrayList<Faixa> lista_faixas = controle.mostrarFaixasdeAlbum(Integer.parseInt(cod_album));
            for(int i = 0; i < lista_faixas.size(); i++){
                listaFaixas.add("COD: " + lista_faixas.get(i).getCod_faixa() + " " +  lista_faixas.get(i).getDescricao());
            }
        }
    }//GEN-LAST:event_BSelecionarAlbumActionPerformed

    private void CriarPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarPlaylistActionPerformed
        Controller controle = new Controller();
        String nome_playlist = nomePlaylist.getText();
        if(nome_playlist.isEmpty() == false){
            ArrayList<Playlist> catalogo = controle.mostrarPlaylists();
            int maior = 0;
            for(int i = 0; i < catalogo.size(); i++){
                if(maior < catalogo.get(i).getCod_playlist()){
                    maior = catalogo.get(i).getCod_playlist();
                }
            }
            int codigo_playlist = maior + 1;
            controle.criarPlaylist(nome_playlist, codigo_playlist, faixas);
            controle.inserirParticipa(codigo_playlist, faixas);
            JOptionPane.showMessageDialog(null, "Playlist criada com sucesso!", "Playlist", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Digite um nome para a playlist", "Playlist", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_CriarPlaylistActionPerformed

    private void bSelecionarFaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSelecionarFaixaActionPerformed
        Controller controle = new Controller();
        if(listaFaixas.getSelectedItem() != null){
            String cod_faixa = listaFaixas.getSelectedItem().split(" ")[1];
            listaFaixasSelecionadas.add(listaFaixas.getSelectedItem());
            listaFaixas.remove(listaFaixas.getSelectedItem());
            Faixa novo = controle.buscarFaixa(Integer.parseInt(cod_faixa));
            faixas.add(novo);
        }
    }//GEN-LAST:event_bSelecionarFaixaActionPerformed

    private void jIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIniciarActionPerformed
        Controller controle = new Controller();
        listaAlbuns.removeAll();
        ArrayList<Album> lista_Albuns = new ArrayList<Album>();
        lista_Albuns = controle.mostrarAlbuns();
        for(int i = 0; i < lista_Albuns.size(); i++){
            listaAlbuns.add("COD: " + lista_Albuns.get(i).getCod_album() + " DESCRIÇÃO: "+ lista_Albuns.get(i).getDescricao());
        }
    }//GEN-LAST:event_jIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriacaoPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriacaoPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriacaoPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriacaoPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriacaoPlaylist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BSelecionarAlbum;
    private javax.swing.JButton CriarPlaylist;
    private javax.swing.JButton bSelecionarFaixa;
    private javax.swing.JButton jIniciar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private java.awt.Label label1;
    private java.awt.List listaAlbuns;
    private java.awt.List listaFaixas;
    private java.awt.List listaFaixasSelecionadas;
    private javax.swing.JTextField nomePlaylist;
    // End of variables declaration//GEN-END:variables
}
