/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import java.util.ArrayList;
import model.Album;
import model.Faixa;
import model.Playlist;

/**
 *
 * @author anderson
 */
public class ModificacaoPlaylist extends javax.swing.JFrame {

    /**
     * Creates new form ModificaçãoPlaylist
     */
    int cod_playlist_selecionada;
    
    public ModificacaoPlaylist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBPlayList = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jDeletar = new javax.swing.JButton();
        listaFaixasPlaylist = new java.awt.List();
        listaPlaylist = new java.awt.List();
        listaFaixa = new java.awt.List();
        jInserir = new javax.swing.JButton();
        jIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PLAYLISTS");

        jLabel2.setText("FAIXAS FORA DA PLAYLIST");

        jBPlayList.setText("SELECIONAR PLAYLIST");
        jBPlayList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPlayListActionPerformed(evt);
            }
        });

        jLabel3.setText("FAIXAS DA PLAYLIST");

        jDeletar.setText("DELETAR FAIXA");
        jDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeletarActionPerformed(evt);
            }
        });

        listaFaixasPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaFaixasPlaylistActionPerformed(evt);
            }
        });

        listaPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaPlaylistActionPerformed(evt);
            }
        });

        jInserir.setText("INSERIR FAIXA");
        jInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInserirActionPerformed(evt);
            }
        });

        jIniciar.setText("INICIAR");
        jIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jBPlayList))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1)))
                .addGap(44, 44, 44)
                .addComponent(listaPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listaFaixasPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(listaFaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(75, 75, 75))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBPlayList))
                    .addComponent(listaPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listaFaixasPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaFaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jIniciar)
                    .addComponent(jDeletar)
                    .addComponent(jInserir))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBPlayListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPlayListActionPerformed
        Controller controle = new Controller();
        ArrayList<Faixa> lista_faixas = new ArrayList<Faixa>();
        if(listaPlaylist.getSelectedItem() != null){
            cod_playlist_selecionada = Integer.parseInt(listaPlaylist.getSelectedItem().split(" ")[1]);
            lista_faixas = controle.mostrarFaixasdePlaylist(cod_playlist_selecionada);
            listaFaixasPlaylist.removeAll();
            for(int i = 0; i < lista_faixas.size(); i++){
                listaFaixasPlaylist.add("COD: " + lista_faixas.get(i).getCod_faixa() + " " + lista_faixas.get(i).getDescricao());
            }
            listaFaixa.removeAll();
            lista_faixas = controle.mostrarFaixasForadePlaylist(cod_playlist_selecionada);
            if(lista_faixas != null){
                for(int j = 0; j < lista_faixas.size(); j++){
                    listaFaixa.add("COD: " + lista_faixas.get(j).getCod_faixa() + " " + lista_faixas.get(j).getDescricao());
                }
            }
        }
    }//GEN-LAST:event_jBPlayListActionPerformed

    private void jDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeletarActionPerformed
        Controller controle = new Controller();
        if(listaFaixasPlaylist.getSelectedItem() != null){
            controle.deletarFaixaDePlaylist(Integer.parseInt(listaFaixasPlaylist.getSelectedItem().split(" ")[1]), cod_playlist_selecionada);
            listaFaixasPlaylist.removeAll();
            ArrayList<Faixa> lista_faixas = new ArrayList<Faixa>();
            listaFaixasPlaylist.removeAll();
            lista_faixas = controle.mostrarFaixasdePlaylist(cod_playlist_selecionada);
            for(int i = 0; i < lista_faixas.size(); i++){
                listaFaixasPlaylist.add("COD: " + lista_faixas.get(i).getCod_faixa() + " "+lista_faixas.get(i).getDescricao());
            }
            listaFaixa.removeAll();
            lista_faixas = controle.mostrarFaixasForadePlaylist(cod_playlist_selecionada);
            if(lista_faixas != null){
                for(int j = 0; j < lista_faixas.size(); j++){
                    listaFaixa.add("COD: " + lista_faixas.get(j).getCod_faixa() + " " + lista_faixas.get(j).getDescricao());
                }
            }
        }
    }//GEN-LAST:event_jDeletarActionPerformed

    private void listaPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaPlaylistActionPerformed

    }//GEN-LAST:event_listaPlaylistActionPerformed

    private void listaFaixasPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaFaixasPlaylistActionPerformed

    }//GEN-LAST:event_listaFaixasPlaylistActionPerformed

    private void jInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInserirActionPerformed
        Controller controle = new Controller();
        if(listaFaixa.getSelectedItem() != null){
            controle.inserirFaixaEmPlaylist(Integer.parseInt(listaFaixa.getSelectedItem().split(" ")[1]) ,cod_playlist_selecionada);
            ArrayList<Faixa> lista_faixas = new ArrayList<Faixa>();
            lista_faixas = controle.mostrarFaixasForadePlaylist(cod_playlist_selecionada);
            listaFaixa.removeAll();
            if(lista_faixas != null){
                for(int j = 0; j < lista_faixas.size(); j++){
                    listaFaixa.add("COD: " + lista_faixas.get(j).getCod_faixa() + " " + lista_faixas.get(j).getDescricao());
                }
            }
            listaFaixasPlaylist.removeAll();
            lista_faixas = controle.mostrarFaixasdePlaylist(cod_playlist_selecionada);
            for(int i = 0; i < lista_faixas.size(); i++){
                listaFaixasPlaylist.add("COD: " + lista_faixas.get(i).getCod_faixa() + " "+lista_faixas.get(i).getDescricao());
            }
        }
    }//GEN-LAST:event_jInserirActionPerformed

    private void jIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIniciarActionPerformed
        listaPlaylist.removeAll();
        listaFaixa.removeAll();
        listaFaixasPlaylist.removeAll();
        Controller controle = new Controller();
        ArrayList<Playlist> lista_p = new ArrayList<Playlist>();
        lista_p = controle.mostrarPlaylists();
        for(int i = 0; i < lista_p.size(); i++){
            listaPlaylist.add("COD: " + lista_p.get(i).getCod_playlist() + " "+ lista_p.get(i).getNome());
        }
    }//GEN-LAST:event_jIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificacaoPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificacaoPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificacaoPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificacaoPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ModificacaoPlaylist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBPlayList;
    private javax.swing.JButton jDeletar;
    private javax.swing.JButton jIniciar;
    private javax.swing.JButton jInserir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private java.awt.List listaFaixa;
    private java.awt.List listaFaixasPlaylist;
    private java.awt.List listaPlaylist;
    // End of variables declaration//GEN-END:variables
}
