/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Playlist;

/**
 *
 * @author anderson
 */
public class SpotperInterface extends javax.swing.JFrame {

    /**
     * Creates new form SpotperInterface
     */
    public SpotperInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bIniciar = new javax.swing.JButton();
        jCriarPlaylist = new javax.swing.JButton();
        jModificarPlaylist = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        listaPlaylist = new java.awt.List();
        reproduzirPlaylist = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bIniciar.setText("INICIAR");
        bIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIniciarActionPerformed(evt);
            }
        });

        jCriarPlaylist.setText("CRIAR PLAYLIST");
        jCriarPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCriarPlaylistActionPerformed(evt);
            }
        });

        jModificarPlaylist.setText("MODIFICAR PLAYLIST");
        jModificarPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModificarPlaylistActionPerformed(evt);
            }
        });

        jLabel1.setText("PLAYLISTS");

        reproduzirPlaylist.setText("REPRODURIR PLAYLIST");
        reproduzirPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reproduzirPlaylistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jModificarPlaylist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCriarPlaylist)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(reproduzirPlaylist)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bIniciar)
                        .addGap(291, 291, 291))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(listaPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addComponent(listaPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(bIniciar)
                .addGap(27, 27, 27)
                .addComponent(reproduzirPlaylist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jModificarPlaylist)
                    .addComponent(jCriarPlaylist))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCriarPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCriarPlaylistActionPerformed
        CriacaoPlaylist novo = new CriacaoPlaylist();
        novo.setVisible(true);
    }//GEN-LAST:event_jCriarPlaylistActionPerformed

    private void jModificarPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jModificarPlaylistActionPerformed
        ModificacaoPlaylist novo = new ModificacaoPlaylist();
        novo.setVisible(true);
    }//GEN-LAST:event_jModificarPlaylistActionPerformed

    private void bIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIniciarActionPerformed
        listaPlaylist.removeAll();
        Controller controle = new Controller();
        ArrayList<Playlist> lista_p = new ArrayList<Playlist>();
        lista_p = controle.mostrarPlaylists();
        for(int i = 0; i < lista_p.size(); i++){
            listaPlaylist.add("COD: " + lista_p.get(i).getCod_playlist() + " Nome: "+ lista_p.get(i).getNome());
        }
    }//GEN-LAST:event_bIniciarActionPerformed

    private void reproduzirPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reproduzirPlaylistActionPerformed
        Controller controle = new Controller();
        if(listaPlaylist.getSelectedItem() != null){
            JOptionPane.showMessageDialog(null, "Reproduzindo playlist selecionada!", "Playlist", JOptionPane.INFORMATION_MESSAGE);
            controle.reproduzirPlaylist(Integer.parseInt(listaPlaylist.getSelectedItem().split(" ")[1]));
        }
    }//GEN-LAST:event_reproduzirPlaylistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpotperInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpotperInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpotperInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpotperInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SpotperInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bIniciar;
    private javax.swing.JButton jCriarPlaylist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jModificarPlaylist;
    private java.awt.List listaPlaylist;
    private javax.swing.JButton reproduzirPlaylist;
    // End of variables declaration//GEN-END:variables
}
